package log_management;

public enum LogEntryName {
    ADD_VERTEX,
    ADD_VERTICES,
    ADD_EDGE,
    ADD_EDGES,
    ADD_SPHERE,
    ADD_ANKER_POINT,
    ADD_ANKER_POINTS,

    REMOVE_VERTEX,
    REMOVE_VERTICES,
    REMOVE_EDGE,
    REMOVE_EDGES,
    REMOVE_SPHERE,
    REMOVE_ANKER_POINT,
    REMOVE_ANKER_POINTS,

    MOVE_VERTEX,
    MOVE_VERTICES,
    MOVE_SPHERE,

    EDIT_SPHERE_COLOR,
    EDIT_SPHERE_SIZE,
    EDIT_SPHERE_ANNOTATION,
    EDIT_VERTEX_COLOR,
    EDIT_VERTEX_FORM,
    EDIT_VERTEX_ANNOTATION,
    EDIT_VERTICES_COLOR,
    EDIT_VERTICES_FORM,
    EDIT_EDGE_FORM,
    EDIT_EDGE_COLOR,
    EDIT_EDGE_TYPE,
    EDIT_EDGE_SIZE,
    EDIT_EDGES_FORM,
    EDIT_EDGES_COLOR,
    EDIT_EDGES_TYPE,
    EDIT_EDGES_SIZE,
    EDIT_FONT,
    EDIT_FONT_SIZE,
    EDIT_LAYOUT,

    ACTIVATE_HIGHLIGHT,
    ACTIVATE_FADEOUT,
    ACTIVATE_ANKER_POINTS_FADEOUT,

    DEACTIVATE_HIGHLIGHT,
    DEACTIVATE_FADEOUT,
    DEACTIVATE_ANKER_POINTS_FADEOUT
}
